### ISSUE TITLE
Templating

### ISSUE THREAD

**Issue by maxcelos** [nucleus-office/nucleus#2]
Criar modulo para a camada visualização.

### Esta isseu depende da finalização da issue #1 .

- [x] Incorporar o temple [startbootstrap-sb-admin-2](https://blackrockdigital.github.io/startbootstrap-sb-admin-2/index.html) na estrutura base do projeto Ref: #1 .
- [x] Implementar HTML da tela de login:
    - Modulo
        - Web
    - Rota:
        - /login
- [x] Implementar HTML da tela reset de senha e e-mail:
    - Modulo
        - Web
    - Rota:
        - /remember-password

**Comment by Diego-Brocanelli** [comment]
- [ ] Incorporar o temple [startbootstrap-sb-admin-2](https://blackrockdigital.github.io/startbootstrap-sb-admin-2/index.html) na estrutura base do projeto Ref: #1 .
- [ ] Implementar HTML da tela de login:
    - Modulo
        - Web
    - Rota:
        - /login
- [ ] Implementar HTML da tela reset de senha e e-mail:
    - Modulo
        - Web
    - Rota:
        - /remember-password

**Comment by maxcelos** [comment]
Feature implementada na PR #6 

@Diego-Brocanelli, favor testar localmente e mover card para "done" se não encontrar erros

**Comment by Diego-Brocanelli** [comment]
Validado, template está excelente.
